# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-19 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contamination_level', models.FloatField(default=0.0, verbose_name='contamination (ng TEQ/kg feed)')),
                ('feed_intake', models.FloatField(default=0.116, verbose_name='feed intake (kg feed/day)')),
                ('exposure_time', models.FloatField(default=0.0, verbose_name='exposure time (days)')),
            ],
        ),
    ]
