# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-19 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('total_teq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedregime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_regime', models.CharField(max_length=200)),
                ('animal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('feed_regime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='total_teq.Feedregime')),
            ],
        ),
        migrations.DeleteModel(
            name='Animals',
        ),
    ]
