# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total_teq', '0002_auto_20170219_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedregime',
            old_name='feed_regime',
            new_name='feed',
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='feed_regime',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='feedregime',
            field=models.ManyToManyField(to='total_teq.Feedregime'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='amount',
            field=models.FloatField(),
        ),
    ]
